import Config from 'react-native-config';
import { getDarkColor, getInitialTheme, isDarkTheme } from '../../AppModules/BaseModule/ColorsHelper';

const mainColors = {
    primaryColor: Config.PRIMARY_APP_COLOR, // based on config, we set primary and secondary color for web in AppNavigation file
    secondary_color: Config.SECONDARY_COLOR,
    foodHubDarkGreen: Config.APP_TYPE === 'FOODHUB' ? '#009A90' : getDarkColor(Config.PRIMARY_APP_COLOR),
    red: '#D82927',
    green: '#009A90',
    blue: '#198EBC',
    purple: '#745CA8',
    yellow: '#FEBE1B',
    orange: '#EF901C',
    ratingYellow: '#FFB400',
    successGreen: '#288702',
    successGreenMild: '#5BAE75',
    whatsappGreen: '#32B000',
    OutrageousOrange: '#FF6733', //used for Gradient 3rd value in wallet,
    hygenicRatingGreen: '#DBDD6D', //default color of hygenic rating widget,
    foodhubPrimaryColor: '#ED515B',
    successGreenLight: '#E7F1E3', //success toast background color,
    errorRedLight: '#F7D4D4', //error toast background color,
    warningYellowLight: '#FFF4D7', //error toast background color,
    lightPink: '#FCFAFF',
    lightSkyBlue: '#EEFFFE',
    defaultBlack: '#111111',
    defaultWhite: '#ffffff',
    darkGrey: '#EEEEEE',
    defaulGrey: '#f9f9f9',
    transparent: 'transparent',
    navbarBackgroundColor: '#fff',
    brownLight: '#AE9E80',
    defaultOverlay: 'rgba(0,0,0,0.7)',
    candyPink: '#f5d7d9',
    azalea: '#fbdcde',
    chipBlack: '#151515',
    lightBorderColor: '#bebebe',
    lightRed: '#FFEFEF',
    lightYellow: '#FEF6E6',
    lightBlue: '#E5EDFF',
    lightWhite: '#BBBBBB',
    customPurple: '#800080',
    fairPink: '#FFEBEB',
    chlorellaGreen: '#5BAE75',
    whatsappLightGreen: '#33CC33',
    acceptGreen: '#5bae75',
    acceptlightGreen: '#aed7bb',
    lightGrey: '#808080',
    mapOverlay: 'rgba(0,0,0,0.2)',
    dullYellow: '#FCC227',
    dullOverlay: 'rgba(255,255,255,0)',
    sunSetOrange: '#f2464c',
    lightGreen: 'rgba(64,173,24,0.15)',
    lightPrimaryRed: 'rgba(216,41,39,0.15)',
    lightWarning: 'rgba(252,194,39,0.15)',
    mildRed: '#FBD7DA',
    mildBlue: '#a9e7ff',
    mildGrey: '#AAAAAA',
    goldYellow: '#FBEBc3',
    defaultGrey: '#f7f7f7',
    greenPostive: '#14AD5C',
    mildYellow: '#FFF5D6',
    borderStorkeNew: '#EAEDF0'
};
const lightTheme = {
    ...mainColors,
    antiFlashWhite: '#EFF8F3', //used for BOGOF and Free lable LinearGradient,
    greenShade: '#C1E6CA', //used for BOGOF and Free lable LinearGradient,
    greenLight: '#E0F8F7', //total savings background color and used for BOGOF and Free lable LinearGradient,
    redLight: '#F7D4D4', //error background color,
    yellowLight: '#FFF4D7', //warning background color,
    yellowShade: '#FFFDF7', // used for item prep time label gradient
    hazelwoodYellow: '#FFF3D4',
    /* BG COLORS */
    black: '#111111',
    white: '#ffffff',
    grey: '#f7f7f7',
    greyDark: '#eeeeee',
    borderColor: '#cccccc',
    iconColor: '#888888',
    darkGrey: '#EDEDED',
    backgroundLight: '#ffffff',
    /* TEXT COLORS */
    textMain: '#111111',
    textGrey: '#555555',
    overlay: 'rgba(0,0,0,0.7)',
    buttonTextColor: '#ffffff',
    navbarMenuSelectedTextColor: '#ED515B',
    candyPink: '#f5d7d9',
    BlueberryColor: '#5c83ef',
    smoothDark: '#eeeeee',
    whiteSmoke: '#EAEAEA',
    lightPrimary: '#FFF2F2',
    whiteOverlay: 'rgba(255,255,255,0)',
    navbarMenuTextColor: '#333333'
};

const darkTheme = {
    ...mainColors,
    antiFlashWhite: '#EFF8F3', //used for BOGOF and Free lable LinearGradient,
    greenShade: '#C1E6CA', //used for BOGOF and Free lable LinearGradient,
    greenLight: '#0B2C2A',
    redLight: '#260604',
    yellowLight: '#413417',
    yellowShade: '#FFFDF7', // used for item prep time label gradient
    hazelwoodYellow: '#FFF3D4',
    /* BG COLORS */
    black: '#ffffff',
    white: '#181818',
    grey: '#0d0d0d',
    greyDark: '#1F1F1F',
    borderColor: '#778491',
    iconColor: '#778491',
    darkGrey: '#111111',
    backgroundLight: '#0d0d0d',
    /* TEXT COLORS */
    textMain: '#ffffff',
    textGrey: '#aaaaaa',
    overlay: 'rgba(255,255,255,0.3)',
    buttonTextColor: '#ffffff',
    BlueberryColor: '#5c83ef',
    smoothDark: '#353535',
    whiteSmoke: '#1F1F1F',
    lightPrimary: '#181818',
    whiteOverlay: 'rgba(0,0,0,0)',
    navbarMenuTextColor: '#aaaaaa'
};
export const getAppInitialTheme = getInitialTheme();

const Colors = isDarkTheme() ? darkTheme : lightTheme;
export default Colors;
